global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app_blue:3000','app_green:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']